### ISSUE TITLE
不能设置主页姓名

### ISSUE THREAD

**Issue by great-xiang** [hooozen/hexo-theme-tranquility#1]
尊敬的作者，您好
请问tranquility是开源的吗？我找不到主页的文件，yml不能设置用户名，主页一直显示hexo

**Comment by great-xiang** [comment]
> 尊敬的作者，您好 请问tranquility是开源的吗？我找不到主页的文件，yml不能设置用户名，主页一直显示hexo

解决了，重新部署就可以了

**Comment by hooozen** [comment]
遵守开源政策 MIT，可以随意修改和发布，只需标注来源
