### ISSUE TITLE
我应该把markdown文件放在哪个文件夹呢？

### ISSUE THREAD

**Issue by AlexStark-cn** [hooozen/hexo-theme-tranquility#10]
我配置了子页，把markdown文件放在了hexo根目录下的public文件夹中的子页名的目录中，然后在markdown文件中加了对应的category，但是打开网页后，我的markdown文章并没有显示在页面中。求大佬指点！

**Comment by hooozen** [comment]
主题没有修改 Hexo 资源文件的储存方式，文章 md 文件应放在 `source/_posts` 目录中，参考[写作｜Hexo](https://hexo.io/zh-cn/docs/writing)。

另外，任何文件都不应该直接放在 public 文件夹中，public 是由 Hexo 自动生成的。

其次，子页功能不需要额外建立子目录，请仔细阅读 README.md，按照介绍开启子页功能并添加对应的 [Front-matter](https://hexo.io/zh-cn/docs/front-matter) 字段即可。

**Comment by AlexStark-cn** [comment]
我知道了，要放在根目录的source的——post文件夹
