### ISSUE TITLE
时间线是否可能设置成三种type默认都显示，而不是只显示“事件”和“App”？

### ISSUE THREAD

**Issue by koanight** [hooozen/hexo-theme-tranquility#11]

**Comment by hooozen** [comment]
现在还不支持配置，但你可以通过修改源代码(https://github.com/hooozen/hexo-theme-tranquility/blob/main/layout/index.njk#L62)设置你想要默认显示的事件，为想要默认显示的 `<input>` 标签添加 `checked` 属性即可。

**Comment by koanight** [comment]
> 现在还不支持配置，但你可以简单地通过修改[源代码](https://github.com/hooozen/hexo-theme-tranquility/blob/main/layout/index.njk#L62)设置你想要默认显示的事件，为想要默认显示的 `<input>` 标签添加 `checked` 属性即可。

添加checked之后，首页黄色图标确实变成实心的，但是并没有显示出对应的列表的文章。点击图标之后可以显示文章，但是样式不对。是否是我配置的不对，[详情请看这里](https://koanight.github.io)

**Comment by hooozen** [comment]
@koanight 不好意思，请尝试修改[源码](https://github.com/hooozen/hexo-theme-tranquility/blob/main/layout/_partials/scripts/Timeline.njk#L29)处，注释掉隐藏 article 的代码：

```js
 // updateList('article', false);
```

**Comment by koanight** [comment]
@hooozen 现在可以了，感谢

**Comment by hooozen** [comment]
已经支持配置化时间线功能，参考 [Release v1.2.0](https://github.com/hooozen/hexo-theme-tranquility/releases/tag/v1.2.0) 和 [README/时间线](https://github.com/hooozen/hexo-theme-tranquility#%E6%97%B6%E9%97%B4%E7%BA%BF)
