### ISSUE TITLE
这套主题有访问人数、文章阅读量吗？

### ISSUE THREAD

**Issue by 1407rean** [hooozen/hexo-theme-tranquility#13]

**Comment by hooozen** [comment]
由于 Hexo 是静态博客，所以这类统计需要接入第三方服务。如果你有好的第三方服务可以推荐一下。

**Comment by hooozen** [comment]
现在还不可以，不过是一个很好的建议，我会更新这个功能

**Comment by 1407rean** [comment]
> 现在还不可以，不过是一个很好的建议，我会更新这个功能

ok

**Comment by Ssvip222** [comment]
为什么我部署的时候git总是报错说是字体有问题，"它无法找到\Hexo\font\SourceHanSerifCN\regular.ttf路径，这可能是由于缺少该字体文件或者其路径配置不正确导致的"  我在网上也找了相关的字体文件  还是不行  是为什么
