### ISSUE TITLE
为什么我部署的时候git总是报错说是字体有问题，"它无法找到\Hexo\font\SourceHanSerifCN\regular.ttf路径，这可能是由于缺少该字体文件或者其路径配置不正确导致的"  我在网上也找了相关的字体文件  还是不行  是为什么

### ISSUE THREAD

**Issue by hooozen** [hooozen/hexo-theme-tranquility#14]
为什么我部署的时候git总是报错说是字体有问题，"它无法找到\Hexo\font\SourceHanSerifCN\regular.ttf路径，这可能是由于缺少该字体文件或者其路径配置不正确导致的"  我在网上也找了相关的字体文件  还是不行  是为什么

_Originally posted by @Ssvip222 in https://github.com/hooozen/hexo-theme-tranquility/issues/13#issuecomment-1519588919_

**Comment by hooozen** [comment]
你在本地使用 hexo s 命令启动服务时回报错吗？

**Comment by Ssvip222** [comment]
已经解决了
