### ISSUE TITLE
请问可以增加一个搜索的功能吗 TvT

### ISSUE THREAD

**Issue by lxQingFeng** [hooozen/hexo-theme-tranquility#18]

**Comment by Hezexian** [comment]
顶，我也想要搜索功能。

**Comment by hooozen** [comment]
> 顶，我也想要搜索功能。

哈哈最近太忙了 我自己都给自己提了很多需求了 等忙完这阵会再慢慢更新

**Comment by hooozen** [comment]
已更新，使用说明见[文章搜索](https://github.com/hooozen/hexo-theme-tranquility?tab=readme-ov-file#%E6%96%87%E7%AB%A0%E6%90%9C%E7%B4%A2).
