### ISSUE TITLE
显示不完整

### ISSUE THREAD

**Issue by lxQingFeng** [hooozen/hexo-theme-tranquility#19]
请问一下 我hexo g生成静态文件的时候，会显示这些东西
![images](https://github.com/lxQingFeng/lxQingFeng.github.io/blob/master/images/111.png)
打开网页时引号也没有显示完
![images](https://github.com/lxQingFeng/lxQingFeng.github.io/blob/master/images/222.png)
![images](https://github.com/lxQingFeng/lxQingFeng.github.io/blob/master/images/333.png)

**Comment by hooozen** [comment]
你使用默认会出现这个问题吗

**Comment by lxQingFeng** [comment]
> 你使用主题的默认配置会出现这个问题吗

默认不会，我自己打进去会莫名少个字或者句号引号

**Comment by hooozen** [comment]
停止 hexo 服务，然后使用 hexo clean 清楚缓存后再启动服务实施

**Comment by lxQingFeng** [comment]
> 停止 hexo 服务，然后使用 hexo clean 清楚缓存后再启动服务实施
还是一样

**Comment by hooozen** [comment]
把浏览器缓存也清除一下

**Comment by lxQingFeng** [comment]
> 把浏览器缓存也清除一下

其实我都试过，您可以去看看
https://ptz191610.cn
每个子页下的文字不是缺字就是缺个标点符号

**Comment by hooozen** [comment]
下图是我访问的截图，你看是你预期的效果吗
![Screenshot_20230528-225201](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/788314ab-2dbb-4a56-a500-67d596630c7a)
![Screenshot_20230528-225155](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/4370087b-9b71-41ae-b54b-057c74e3659f)
![Screenshot_20230528-225130](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/4f48303a-f8db-4ddc-a86b-fc3f5c76830f)

**Comment by lxQingFeng** [comment]
> 下图是我访问的截图，你看是你预期的效果吗
> ![Screenshot_20230528-225201](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/788314ab-2dbb-4a56-a500-67d596630c7a)
> ![Screenshot_20230528-225155](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/4370087b-9b71-41ae-b54b-057c74e3659f)
> ![Screenshot_20230528-225130](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/4f48303a-f8db-4ddc-a86b-fc3f5c76830f)
> 

不是，这些字都有缺失，您可以从 F12 看到那些字原来的样子。

**Comment by hooozen** [comment]
我没理解你的意思，我现在也不方便用电脑，你可以用截下图标注一下缺少了哪些字体吗

**Comment by lxQingFeng** [comment]
> 我没理解你的意思，我现在也不方便用电脑，你可以用截下图标注一下缺少了哪些字体吗

![正在上传 IMG_20230528_231717.png…]()
类似这样，这个缺了两个句号，其他的会缺字缺标点符号。

**Comment by hooozen** [comment]
我已经重现并定位了问题，这是一个 BUG！下个版本将修复这它。非常感谢提出这个问题！

你可以通过以下方法临时解决这个问题：

手动修改主题目录下 [/scripts/generaotr/font.js](https://github.com/hooozen/hexo-theme-tranquility/blob/main/scripts/generator/font.js#L64) 第 64 行代码，为子字符串添加半角空格，并为所有出现的半角字符（英文字母和符号）添加对应的**大小写**以及**全角**字符。例如下面的代码在最后添加的字符串解决了不能正常显示中文左引号，和英文字母 z B F 以及半角逗号的问题：

```js
return Array.from(new Set(text)).sort().join("") + " Ｂ，ａＦZ"
```

**Comment by hooozen** [comment]
已更新修复了该 bug，请查看 [release v1.2.2](https://github.com/hooozen/hexo-theme-tranquility/releases/tag/v1.2.2)
