### ISSUE TITLE
无法创建文章

### ISSUE THREAD

**Issue by cjq0911** [hooozen/hexo-theme-tranquility#2]
您好，我在使用您的主题时，创建文章后会报错，在页面中博客里的文章一直在加载，这是什么问题呀
![图片](https://user-images.githubusercontent.com/121212157/209175359-31f0de6b-2873-41e2-b663-6ff9e50ad92f.png)

**Comment by hooozen** [comment]
你是用的 1.0.1 版本吗，有没有安装hexo-related-popular-posts 插件

**Comment by hooozen** [comment]
已更新 v1.0.2，请查看是否解决了该问题。

**Comment by cjq0911** [comment]
感谢作者，现在已经好使了

**Comment by cjq0911** [comment]
感谢作者，现在已经好使了
