### ISSUE TITLE
如何添加mathjax的components组件支持

### ISSUE THREAD

**Issue by hiltay** [hooozen/hexo-theme-tranquility#24]
之前看到您的博客上使用了[Contextual Menu Options](https://docs.mathjax.org/en/latest/options/menu.html#menu-options)组件，请问[hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax)是怎么配置呢

**Comment by hooozen** [comment]
您好，你看我之前博客使用 MathJax 的右键菜单是因为我当时使用的是前端渲染.  

至于 [hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax) 如何配置,  我简单浏览了下该插件的源码,  似乎并不支持配置该选项.  

我在文档[[配置-数学公式]](https://github.com/hooozen/hexo-theme-tranquility#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F)中之所以推荐使用该插件是出于性能考虑，所以具体的使用哪种方式还要看你的需求.  

当然不排除 [hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax) 插件后续更新更多的选项,  请自行关注.

**Comment by hiltay** [comment]
感谢解答，我也去[hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax)下提问了，大概明白前端和后端渲染了。
参考您代码中的引用 https://github.com/hooozen/hexo-theme-tranquility/blob/a1cbe0ae89558d1723bf1e3b235471042b2c2416/layout/_partials/layout.njk#L150-L154
和官方文档的说明，在[hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax)添加支持前，改为前端渲染，可以正常配置组件。
