### ISSUE TITLE
无法启动，能帮我看看怎么回事吗

### ISSUE THREAD

**Issue by Marcos0221** [hooozen/hexo-theme-tranquility#27]
没办法启动，报错信息如下
<img width="500" alt="image" src="https://github.com/hooozen/hexo-theme-tranquility/assets/73690771/e436fefa-2845-47f9-8b1e-cd19a774b28c">

**Comment by hooozen** [comment]
请参考 #26 ：https://github.com/hooozen/hexo-theme-tranquility/issues/26#issuecomment-1713625900
