### ISSUE TITLE
请问这个是为什么呢？

### ISSUE THREAD

**Issue by SY2023-1** [hooozen/hexo-theme-tranquility#28]
![image](https://github.com/hooozen/hexo-theme-tranquility/assets/145232591/6964fb3e-f42a-428a-b93b-90e6388b0c48)

**Comment by hooozen** [comment]
根据报错应该是配置文件未正确配置，请参考[使用文档-安装](https://github.com/hooozen/hexo-theme-tranquility#%E5%AE%89%E8%A3%85)

**Comment by SY2023-1** [comment]
![image](https://github.com/hooozen/hexo-theme-tranquility/assets/145232591/ce107572-7797-4349-a6fb-a0e9a8446ad4)
你好，这里我按照说明配置了仍然报错，是什么原因呢？

**Comment by hooozen** [comment]
你好，这是缺少部分依赖导致的，可以查看最新的[更新说明](https://github.com/hooozen/hexo-theme-tranquility/releases/tag/v1.3.2)安装相关的依赖
