### ISSUE TITLE
关于文章描述无法显示问题

### ISSUE THREAD

**Issue by ErMaoZhou** [hooozen/hexo-theme-tranquility#33]
哈哈哈新年快乐，看起来是新年的第一个问题。

**一、文章描述无法显示**
我在文章中配置了description这个字段，但是在网站中无法正确显示。
![md文件中的头部信息配置](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/110c72f8-914d-45ac-a612-4ad26453ee38)

效果图如下：
![效果图1](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/78c7d7da-81ce-4b21-a1fd-2513d2bcc15f)

其中_config.yml配置文件如下图所示：
![_config yml配置文件1](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/328ef079-6056-416a-abe5-1fe91742c82e)
![_config yml配置文件2](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/32405b93-1c47-42dd-b7c2-c5cdcb939306)
![_config yml配置文件3](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/3de46099-0b10-465f-901a-827d60fd2ad4)

_config.tranquility.yml配置文件如下图所示：
![_config tranquility yml配置图片1](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/840f2cc5-8aa2-4d1f-bb88-e7ada28d150a)
![_config tranquility yml配置图片2](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/be03fd56-3050-408f-81a4-707a121f5192)
![_config tranquility yml配置图片3](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/02bb2553-14c7-4ab9-8e91-60c002c544fb)
![_config tranquility yml配置图片4](https://github.com/hooozen/hexo-theme-tranquility/assets/109649163/5d20662d-0f42-4b38-b974-eac71b65485e)

谢谢！

**Comment by hooozen** [comment]
你好，新年快乐！
文章的介绍不是使用配置文件配置的，详情请参考 hexo 的官方文档:https://hexo.io/zh-cn/docs/tag-plugins#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81%E5%92%8C%E6%88%AA%E6%96%AD

**Comment by ErMaoZhou** [comment]
> 你好，新年快乐！ 文章的介绍不是使用配置文件配置的，详情请参考 hexo 的官方文档:https://hexo.io/zh-cn/docs/tag-plugins#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81%E5%92%8C%E6%88%AA%E6%96%AD

非常感谢回答！
我已经发现使用 可以实现文章摘要的效果了。

但是我想文章也像博客一样，有一个description，只在文章简介中显示，不在文章内容中显示，似乎hexo主题并不支持这个功能。如果后续可以添加就更好啦！再次感谢回答！

**Comment by hooozen** [comment]
好的，下次更新会考虑增加这个功能，谢谢反馈！
