### ISSUE TITLE
友链能否调整？

### ISSUE THREAD

**Issue by xiaoyangst** [hooozen/hexo-theme-tranquility#44]
随着好友增多，网页就会拉长，考虑出一个专门存放友链或横向排布友链吗？

**Comment by hooozen** [comment]
能否提供下截图或链接看下具体的拉长后是什么样的效果

**Comment by xiaoyangst** [comment]
> 能否提供下截图或链接看下具体的拉长后是什么样的效果

![image](https://github.com/user-attachments/assets/6afb5155-9667-4461-8fd6-67e9efc3d50f)

这不就越来越长吗？但是很多空间都没有被用到，随着好友增多，就很丑陋。有考虑单独出一个模块来存储友链吗？

**Comment by hooozen** [comment]
了解了 后续会考虑重新设计或增加单独的页面

**Comment by xiaoyangst** [comment]
> 了解了 后续会考虑重新设计或增加单独的页面

OK！！！

**Comment by hooozen** [comment]
先打开 issue 哈 方便记录

**Comment by xiaoyangst** [comment]
> 先打开 issue 哈 方便记录

好的，你随意

**Comment by hooozen** [comment]
该问题已经在 [v1.3.5](https://github.com/hooozen/hexo-theme-tranquility/releases/tag/v1.3.5) 版本修复.
