### ISSUE TITLE
index.html和md文件头怎么设置呀？

### ISSUE THREAD

**Issue by great-xiang** [hooozen/hexo-theme-tranquility#5]
我在网上找了一些资料，都是说设置tags和categories的，但是怎么设置type呀，我试了好几种格式，都不行，要么子页显示空，要么子页显示全部文章。

我的index文件设置：
---
title: 我的思想介绍
date: 2022-12-22 23:43:55
type: ”tags“
comments: true
---

我的md文件头设置：
---
title: 我的世界观
date: 2022-12-22 23:43:55
tags: me
---

**Comment by hooozen** [comment]
categories 用来设置属于哪一个子页，例如，如果你设置了一个名为 life 的子页为，则应该在想划分到该子页的文章头部设置 categorie: life 

tags 的作用和意义没有改变，参考 Hexo 官方文档。

type 是用来设置展示在首页的“时间线”的功能的，具体参考 readme，这个功能下一个 feature 会更新。



index.html 的内容在主题 config 里进行简单配置
，也可以手动修改源码

**Comment by great-xiang** [comment]
谢谢大佬解答我的疑问，(*^▽^*)
