### ISSUE TITLE
关于”时间线”功能的图片添加

### ISSUE THREAD

**Issue by YRiccch** [hooozen/hexo-theme-tranquility#6]
我觉得可以在时间线功能的旁边设置图片功能，这样可以使得很遥远的记忆在看到图片的一瞬间，让尘封的记忆被唤醒，单纯的文字可能在唤醒记忆这一方面的效果还是没有图片来的那么强烈。

**Comment by hooozen** [comment]
时间线的设计初衷在于展示个人重要履历和作品，另一方面，图片占用的空间比较大，可能需要重新进行界面设计。不过还是非常感谢你提出的建议，我会在适当时候考虑这个需求。
