### ISSUE TITLE
启动不了，是不是有什么文件没修改，帮助文档没提到？

### ISSUE THREAD

**Issue by CloudSVC** [hooozen/hexo-theme-tranquility#7]
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.

**Comment by hooozen** [comment]
这个警告是依赖库的警告，是不影响启动的。配置文件有没有对应更新？

**Comment by CloudSVC** [comment]
> 这个警告是依赖库的警告，是不影响启动的。配置文件有没有对应更新？

是的，是没有更新配置的问题，已经成功了
