### ISSUE TITLE
字体缺失

### ISSUE THREAD

**Issue by nf173** [hooozen/hexo-theme-tranquility#8]
思源字体部分字体缺失，如”一“、”久“等字体显示不出来

**Comment by hooozen** [comment]
我做了测试，“一”和“久”是可以显示出来的，如下：

<img width="957" alt="image" src="https://user-images.githubusercontent.com/24765496/224962014-51a3e63d-f95b-4a95-85da-929850aa86fd.png">

上一个版本是有字体缺失的BUG，最新版本做了修复，是否使用了最新版本？
另外，汉字压缩只支持主题设置的 CSS 样式部分，其余部分是不被压缩的，例如正文部分的文字不会被写入子字体，这是考虑到正文内容文字太多，导致字体文件过大。

**Comment by nf173** [comment]
今天看了下显示正常了，很奇怪

**Comment by hooozen** [comment]
之前有使用上一个版本发布过博客吗？如果有的话可能是字体文件网络缓存造成的吧。
